name: NiaoCloud_checkin

on:
  
  #push: # push触发
  #  branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '30 13,22 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时(4-23)
    
jobs:
  daily-task:
    if: github.event.repository.owner.id == github.event.sender.id

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.5]
        node-registry: ['https://registry.npmjs.org']

    steps:
    
    # 检出
    #- name: Checkout
    #  uses: actions/checkout@v2
      
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ matrix.node-registry }}

    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - name: restore npm cache
      uses: actions/cache@v2
      id: use-npm-cache
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: restore npm dependencies
      uses: actions/cache@v2
      id: use-npm-depends
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-depends-${{ hashFiles('**/package-lock.json') }} 

    - name: restore task cache
      uses: actions/cache@v2
      id: use-task-cache
      with: 
        path: |
          /home/runner/.niaocloud
        key: ${{ runner.os }}-task-${{ hashFiles('**/package-lock.json') }}

    #- name: Install dependencies
    #  if: steps.use-npm-cache.outputs.cache-hit != 'true' || steps.use-npm-depends.outputs.cache-hit != 'true'
    #  run: npm install

    - name: Run niaocloud
      run: |
         git clone -b main https://github.com/hbstarjason2021/jd-scripts-docker.git ~/jd-scripts-docker
         cd ~/jd-scripts-docker
         export NIAO_CLOUD_COOKIES="${{secrets.NIAO_CLOUD_COOKIES}}"
         #npm install
         pwd
         node -v 
         node niaocloud.js
